### ISSUE TITLE
mine-trxml fails when trxml is empty

### ISSUE THREAD

**Issue by tilaboy** [tilaboy/xml-miner#2]
```
Traceback (most recent call last):
  File "/Users/chao/anaconda3/bin/trxml-python-select", line 11, in <module>
    load_entry_point('xml-miner==0.0.0', 'console_scripts', 'trxml-python-select')()
  File "/Users/chao/anaconda3/lib/python3.6/site-packages/xml_miner-0.0.0-py3.6.egg/xml_miner/mine_trxml.py", line 75, in main
    trxml_miner.mine(data, args.output_file)
  File "/Users/chao/anaconda3/lib/python3.6/site-packages/xml_miner-0.0.0-py3.6.egg/xml_miner/miner.py", line 183, in mine
    selected_values = self.selectors.select_trxml_fields(trxml_obj)
  File "/Users/chao/anaconda3/lib/python3.6/site-packages/xml_miner-0.0.0-py3.6.egg/xml_miner/selectors/trxml_selectors.py", line 84, in select_trxml_fields
    selected = self._select_singletons(trxml)
  File "/Users/chao/anaconda3/lib/python3.6/site-packages/xml_miner-0.0.0-py3.6.egg/xml_miner/selectors/trxml_selectors.py", line 142, in _select_singletons
    for selector in self.selectors
  File "/Users/chao/anaconda3/lib/python3.6/site-packages/xml_miner-0.0.0-py3.6.egg/xml_miner/selectors/trxml_selectors.py", line 142, in <dictcomp>
    for selector in self.selectors
  File "/Users/chao/anaconda3/lib/python3.6/site-packages/xml_miner-0.0.0-py3.6.egg/xml_miner/selectors/trxml_selector.py", line 79, in select_value_with_xpath
    element = self.select_field_with_xpath(xml_tree)
  File "/Users/chao/anaconda3/lib/python3.6/site-packages/xml_miner-0.0.0-py3.6.egg/xml_miner/selectors/trxml_selector.py", line 73, in select_field_with_xpath
    return xml_tree.working_entity.find(self.xpath)
AttributeError: 'NoneType' object has no attribute 'find'
```

**Comment by tilaboy** [comment]
fixed in v0.0.3
